server:
  port: 80

spring:
  application:
    name: srv2
  cloud:
    config:
      uri: http://config/
      profile: sit
      discovery:
        service-id: config
    inetutils:
      preferred-networks:
        - 10.1
        
eureka:
  instance:
    hostname: eureka
    port: 8000
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
      

          