eureka:
  instance:
    hostname: localhost
  server:
    renewalPercentThreshold: 0.49
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
