server:
  port: 80

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JamesLiu104696/cld.git
          search-paths: /**
          username: JamesLiu104696
          password: Test135790
    inetutils:
      preferred-networks:
        - 10.1
eureka:
  instance:
    hostname: 192.168.5.203
    port: 8000
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
      

          