server:
  port: 80

spring:
  application:
    name: zuul
  profiles:
    active: dev
    

zuul:
  routers:
    service1:
      path: /v1/**
      serviceId: srv1
    service2:
      path: /v2/**
      serviceId: srv2
